name: JS Actions

on: [pull_request]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: welcome
        uses: ./.github/actions/welcome
        with:
          labels: "${{github.event.pull_request.labels.*.name}}"
          repo-token: ${{secrets.GITHUB_TOKEN}}
