name: JS Actions

on: [pull_request]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: welcome
        if: contains(github.event.pull_request.labels.*.name, 'frontend')
        uses: ./.github/actions/welcome
 
 
